%%{
  init: {
    'theme': 'redux-dark-color'
  }
}%%
erDiagram
    Location ||--o{ Event : "hosts"
    Location ||--o{ Seat : "contains"
    Seat |o--o{ Ticket : "is reserved in"
    Event ||--o{ Ticket : "issues"
    Event_categories ||--o{ Event : "categorizes"
    Event_genres |o--o{ Event : "specifies"
    Customer ||--o{ Ticket : "purchases"
    Ticket ||--o| Payment : "requires"
    Customer }o--o{ Event : "favourites"
    
    Customer ||--o{ Review : "writes"
    Event ||--o{ Review : "receives"

    Location {
        int location_id PK
        string city
        string address
        int number_of_seats
    }

    Event {
        int event_id PK
        int location_id FK
        int category_id FK
        int genre_id FK
        datetime event_date
        time start_time
        string event_name
    }

    Event_categories {
        int category_id PK
        string category_name
    }

    Event_genres {
        int genre_id PK
        string genre_name
    }

    Customer {
        int customer_id PK
        string email
        string phone_number
        string name
    }

    Ticket {
        int ticket_id PK
        int event_id FK
        int customer_id FK
        int seat_id FK
        decimal ticket_price
    }

    Payment {
        int payment_id PK
        int ticket_id FK
        datetime payment_time
        string payment_method
        string status
        decimal amount
    }

    Seat {
        int seat_id PK
        int location_id FK
        int sector_id
    }

    Review {
        int review_id PK
        int customer_id FK
        int event_id FK
        int rating
        string comment
        datetime created_at
    }