@startuml event_system

left to right direction
skinparam packageStyle rectangle

skinparam actorStyle awesome
skinparam usecase {
    BackgroundColor LightPink
    BorderColor DarkSlateGray
    ArrowColor DarkSlateGray
}

actor "Guest" as Guest
actor "Customer" as Customer
actor "Admin" as Admin

Customer -up-|> Guest

rectangle "Event Ticketing System" {
    'for guest
    usecase "search and filter events\n(city, genre, category)" as UC1
    usecase "see event details\n(location, available seats, price)" as UC2

    'for customer
    usecase "check history of attended events" as UC3
    usecase "create an account" as UC4
    usecase "edit profile" as UC5
    usecase "add event to favourite list" as UC6
    usecase "buy ticket" as UC7
    usecase "receive a ticket by email or download ticket" as UC8
    usecase "use promocodes or certificates" as UC9
    usecase "request ticket refund" as UC16
    usecase "leave a review or rating" as UC17

    'for admin
    usecase "add an event" as UC10
    usecase "edit/cancel event" as UC11
    usecase "view analytics" as UC12
    usecase "view list of registered customers" as UC13
    usecase "make a ticket refund" as UC14
    usecase "manage promocodes and discounts" as UC15
    usecase "scan ticket" as UC18
}

Guest --> UC1
Guest --> UC2
Guest --> UC4

Customer --> UC3
Customer --> UC5
Customer --> UC6
Customer --> UC7
Customer --> UC16

Admin --> UC4
Admin --> UC10
Admin --> UC12
Admin --> UC13
Admin --> UC14
Admin --> UC15
Admin --> UC18



UC9 .> UC7 : <<extend>>
UC8 .> UC7 : <<extend>>
UC16 .> UC7 : <<extend>>
UC17 .> UC3 : <<extend>>
UC11 .> UC10 : <<extend>>

@enduml